// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

console.log("DATABASE_URL:", process.env.DATABASE_URL);
console.log("Gemini_API_KEY:", process.env.GOOGLE_API_KEY);


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {

    url: process.env["DATABASE_URL"],
  },
});
